# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class:  MyBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.subscriber.authentification:
        class: MyBundle\Subscriber\AuthSubscriber
        arguments: [ "@doctrine" ]
        tags:
            - { name: kernel.event_subscriber, priority: 2 }

    mybundle.util.user_manipulator:
        class: MyBundle\Util\UserManipulator
        arguments: [ "@fos_user.user_manager", "@event_dispatcher", "@request_stack" ]

