<?php

namespace MyBundle\Repository;

/**
 * HeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeroRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByName($name,$mode=3)
    {
        // $mode = array("strict","start","end","whatever");
        switch($mode){
            case 0:
                $param = "$name";
                break;
            case 1:
                $param = "$name%";
                break;
            case 2:
                $param = "%$name";
                break;
            case 3:
                $param = "%$name%";
                break;
        }

        $query =  $this->createQueryBuilder("hero")
            ->select()
            ->where('hero.name LIKE :name ')
            ->setParameter('name', $param)
            ->getQuery();
        $result = $query->getResult();
        return $result;
    }
}
