<?php

namespace MyBundle\Repository;

/**
 * ThemePlaceMapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemePlaceMapRepository extends \Doctrine\ORM\EntityRepository
{
}
